import sqlite3
conn = sqlite3.connect(r'C:\Users\pohi9\.n8n\database.sqlite')
conn.execute('PRAGMA wal_checkpoint(FULL)')
cur = conn.cursor()
cur.execute("SELECT email, password FROM user WHERE email='peterpohankapersonal@gmail.com'")
row = cur.fetchone()
print('Email:', row[0])
print('Hash prefix:', row[1][:30])
conn.close()
print('Checkpoint done')
