import fs from "node:fs";
import os from "node:os";
import path from "node:path";

export interface DocsConfigFixture {
  rootDir: string;
  cleanup: () => void;
}

function writeFile(rootDir: string, relativePath: string, content: string): void {
  const absolutePath = path.join(rootDir, relativePath);
  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.writeFileSync(absolutePath, content, "utf8");
}

export function createDocsConfigFixture(): DocsConfigFixture {
  const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), "brunella-docs-config-"));

  writeFile(
    rootDir,
    "README.md",
    [
      "# Brunella",
      "",
      "<!-- DOC_STATS_START -->",
      "managed docs block",
      "<!-- DOC_STATS_END -->",
      "",
      "OLLAMA_BASE_URL=https://ollama.example",
      "GITHUB_PAT=ghp_example",
      "BRUNELLA_WORKSPACE_ROOT=.",
    ].join("\n"),
  );

  writeFile(
    rootDir,
    "BRUNELLA_MASTER_CONTEXT.md",
    [
      "# Master Context",
      "",
      "**Ez a dokumentum automatikusan generált. Ne szerkeszd kézzel!**",
      "",
      "OLLAMA_BASE_URL=https://ollama.example",
      "GITHUB_PAT=ghp_example",
    ].join("\n"),
  );

  writeFile(
    rootDir,
    path.join("docs", "RENDSZER.md"),
    [
      "# Rendszer",
      "",
      "OLLAMA_BASE_URL=https://ollama.example",
      "BRUNELLA_WORKSPACE_ROOT=.",
    ].join("\n"),
  );

  for (const relativePath of [
    "BOOTSTRAP.md",
    path.join("docs", "PROJEKT_DIAGRAM.md"),
    ".ai/BOOTSTRAP.md",
    ".vscode/BOOTSTRAP.md",
  ]) {
    writeFile(
      rootDir,
      relativePath,
      [
        "# Managed Doc",
        "",
        "<!-- DOC_STATS_START -->",
        "managed docs block",
        "<!-- DOC_STATS_END -->",
        "",
        "OLLAMA_BASE_URL=https://ollama.example",
      ].join("\n"),
    );
  }

  writeFile(
    rootDir,
    "conductor/tracks.md",
    [
      "# Tracks",
      "",
      "*Auto-generated by Track State Manager v2.0*",
      "",
      "GITHUB_PAT=ghp_example",
    ].join("\n"),
  );

  writeFile(
    rootDir,
    ".env.example",
    [
      "OLLAMA_BASE_URL=https://ollama.example",
      "GITHUB_PAT=ghp_example",
      "BRUNELLA_WORKSPACE_ROOT=.",
    ].join("\n"),
  );

  writeFile(
    rootDir,
    "paios.config.yaml",
    [
      "# PAIOS 1.0 Unified Configuration",
      "api_key_env: GITHUB_PAT",
      "base_url_env: OLLAMA_BASE_URL",
      "workspace_root_env: BRUNELLA_WORKSPACE_ROOT",
    ].join("\n"),
  );

  writeFile(
    rootDir,
    "src/config/schema.ts",
    [
      "import { z } from 'zod';",
      "",
      "// Config Validation with Zod",
      "export const envSchema = z.object({",
      "  OLLAMA_BASE_URL: z.string(),",
      "  GITHUB_PAT: z.string(),",
      "  BRUNELLA_WORKSPACE_ROOT: z.string(),",
      "});",
    ].join("\n"),
  );

  writeFile(
    rootDir,
    "src/config/index.ts",
    [
      "export const config = {",
      "  ollama: process.env.OLLAMA_BASE_URL ?? '',",
      "  workspaceRoot: process.env.BRUNELLA_WORKSPACE_ROOT ?? '.',",
      "};",
    ].join("\n"),
  );

  writeFile(
    rootDir,
    "src/config/paiosConfig.ts",
    [
      "export const paiosConfig = {",
      "  apiKey: process.env.GITHUB_PAT ?? '',",
      "};",
    ].join("\n"),
  );

  writeFile(
    rootDir,
    "src/core/bifrost_gateway.ts",
    [
      "export const bifrost = {",
      "  baseUrl: process.env.OLLAMA_BASE_URL ?? '',",
      "};",
    ].join("\n"),
  );

  writeFile(
    rootDir,
    "src/utils/cliConfig.ts",
    [
      "export const BrunellaSettingsSchema = {",
      "  workspaceRoot: process.env.BRUNELLA_WORKSPACE_ROOT ?? '.',",
      "};",
    ].join("\n"),
  );

  return {
    rootDir,
    cleanup: () => {
      fs.rmSync(rootDir, { recursive: true, force: true });
    },
  };
}

