
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-core",
  "version": "0.3.0",
  "versions": {
    "@openai/agents-core": "0.3.0",
    "openai": "^6"
  }
};

export default METADATA;
