import type { HookCatalogEntry } from '../hookRegistry.js';

export const BUILTIN_HOOK_CATALOG: HookCatalogEntry[] = [
  { event: 'webhook.received', category: 'infra', description: 'Altalanos webhook ingress hook', priority: 7, timeoutMs: 10_000, retryOnFail: false },
  { event: 'github.push', category: 'infra', description: 'GitHub push webhook hook', priority: 7, timeoutMs: 10_000, retryOnFail: false },
  { event: 'tool:before', category: 'lifecycle', description: 'MCP tool futas elotti hook', priority: 8, timeoutMs: 5_000, retryOnFail: false },
  { event: 'tool:after', category: 'lifecycle', description: 'MCP tool futas utani hook', priority: 8, timeoutMs: 5_000, retryOnFail: true },
  { event: 'tool:error', category: 'lifecycle', description: 'MCP tool hiba hook', priority: 9, timeoutMs: 5_000, retryOnFail: true },
  { event: 'n8n:workflow:completed', category: 'business', description: 'n8n workflow sikeres visszahivas', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'n8n:workflow:failed', category: 'business', description: 'n8n workflow hiba visszahivas', priority: 8, timeoutMs: 10_000, retryOnFail: true },
  { event: 'n8n:workflow:timeout', category: 'business', description: 'n8n workflow timeout hook', priority: 9, timeoutMs: 10_000, retryOnFail: true },
  { event: 'sdlc:phase:before', category: 'lifecycle', description: 'SDLC fazis indulasa elotti hook', priority: 7, timeoutMs: 10_000, retryOnFail: false },
  { event: 'invoice:received', category: 'business', description: 'Bejovo szamla feldolgozas indito hook', priority: 10, timeoutMs: 15_000, retryOnFail: true },
  { event: 'invoice:ocr:start', category: 'business', description: 'Szamla OCR indito hook', priority: 9, timeoutMs: 15_000, retryOnFail: true },
  { event: 'invoice:ocr:done', category: 'business', description: 'Szamla OCR befejezes hook', priority: 9, timeoutMs: 15_000, retryOnFail: true },
  { event: 'invoice:nav:validated', category: 'business', description: 'NAV validalt szamla hook', priority: 9, timeoutMs: 15_000, retryOnFail: true },
  { event: 'invoice:sheets:synced', category: 'business', description: 'Google Sheets szinkron hook szamlahoz', priority: 8, timeoutMs: 15_000, retryOnFail: true },
  { event: 'invoice:approved', category: 'business', description: 'Jovahagyott szamla hook', priority: 8, timeoutMs: 10_000, retryOnFail: true },
  { event: 'nav:invoice:submitted', category: 'business', description: 'NAV invoice submission hook', priority: 8, timeoutMs: 10_000, retryOnFail: true },
  { event: 'inventory:stock:changed', category: 'business', description: 'Keszlet valtozas hook', priority: 8, timeoutMs: 10_000, retryOnFail: true },
  { event: 'finance:transaction:recorded', category: 'business', description: 'Penzugyi tranzakcio rogzites hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'finance:anomaly:detected', category: 'security', description: 'Penzugyi anomalia detektalva', priority: 9, timeoutMs: 10_000, retryOnFail: true },
  { event: 'market:price:changed', category: 'business', description: 'Piaci arvaltozas hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'grant:new:found', category: 'business', description: 'Uj palyazati lehetoseg hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'hr:leave:requested', category: 'business', description: 'Szabadsagigeny hook', priority: 8, timeoutMs: 10_000, retryOnFail: true },
  { event: 'crm:lead:created', category: 'business', description: 'UJ CRM lead erkezett', priority: 9, timeoutMs: 10_000, retryOnFail: true },
  { event: 'sales:email:sent', category: 'business', description: 'Sales outreach email elkuldve', priority: 6, timeoutMs: 10_000, retryOnFail: true },
  { event: 'logistics:delay:detected', category: 'business', description: 'Logisztikai keses detektalva', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'email:classified', category: 'business', description: 'Email triage klasszifikacios hook', priority: 9, timeoutMs: 10_000, retryOnFail: true },
  { event: 'email:sentiment:negative', category: 'business', description: 'Negativ hangvetelu email hook', priority: 8, timeoutMs: 10_000, retryOnFail: true },
  { event: 'git:pre:commit', category: 'infra', description: 'Pre-commit fejlesztoi vedohook', priority: 8, timeoutMs: 10_000, retryOnFail: false },
  { event: 'file:changed', category: 'infra', description: 'Fajlvaltozas hook', priority: 6, timeoutMs: 5_000, retryOnFail: false },
  { event: 'file:created:root', category: 'infra', description: 'Gyokerkonyvtarba uj fajl kerult', priority: 7, timeoutMs: 5_000, retryOnFail: false },
  { event: 'reflection:pattern:identified', category: 'learning', description: 'Reflexios mintafelismeresi hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'golden:dataset:milestone', category: 'learning', description: 'Golden dataset merfoldko hook', priority: 6, timeoutMs: 5_000, retryOnFail: false },
  { event: 'agent:task:completed', category: 'learning', description: 'Agent feladat befejezese hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'agent:task:failed', category: 'learning', description: 'Agent feladat hiba hook', priority: 8, timeoutMs: 10_000, retryOnFail: true },
  { event: 'agent:performance:drift', category: 'learning', description: 'Agent teljesitmeny drift hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'track:status:changed', category: 'learning', description: 'Conductor track statuszvaltozas hook', priority: 8, timeoutMs: 10_000, retryOnFail: true },
  { event: 'track:completed', category: 'learning', description: 'Conductor track befejezesi hook', priority: 8, timeoutMs: 10_000, retryOnFail: true },
  { event: 'track:phase:architect:completed', category: 'learning', description: 'Architect fazis lezaras hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'kernel:phase:start', category: 'infra', description: 'Kernel fazis start hook', priority: 7, timeoutMs: 5_000, retryOnFail: false },
  { event: 'kernel:phase:timeout', category: 'infra', description: 'Kernel fazis timeout hook', priority: 9, timeoutMs: 5_000, retryOnFail: true },
  { event: 'kernel:critic:failed', category: 'infra', description: 'Kernel critic hiba hook', priority: 9, timeoutMs: 5_000, retryOnFail: true },
  { event: 'dag:execution:completed', category: 'infra', description: 'DAG workflow befejezodes hook', priority: 7, timeoutMs: 5_000, retryOnFail: false },
  { event: 'swarm:colony:overloaded', category: 'infra', description: 'Swarm tulterheles hook', priority: 8, timeoutMs: 5_000, retryOnFail: true },
  { event: 'swarm:colony:idle', category: 'infra', description: 'Swarm idle hook', priority: 5, timeoutMs: 5_000, retryOnFail: false },
  { event: 'cean:worker:error', category: 'infra', description: 'CEAN worker hiba hook', priority: 8, timeoutMs: 5_000, retryOnFail: true },
  { event: 'llm:provider:failed', category: 'infra', description: 'LLM provider kieses hook', priority: 9, timeoutMs: 5_000, retryOnFail: true },
  { event: 'llm:provider:restored', category: 'infra', description: 'LLM provider helyreallas hook', priority: 7, timeoutMs: 5_000, retryOnFail: false },
  { event: 'llm:cache:hit', category: 'infra', description: 'LLM cache hit hook', priority: 5, timeoutMs: 5_000, retryOnFail: false },
  { event: 'llm:cost:threshold', category: 'infra', description: 'LLM koltseg kuszob hook', priority: 8, timeoutMs: 5_000, retryOnFail: true },
  { event: 'security:permission:denied', category: 'security', description: 'RBAC tiltott muvelet hook', priority: 10, timeoutMs: 5_000, retryOnFail: true },
  { event: 'security:sandbox:escape:attempt', category: 'security', description: 'Sandbox kitoresi kiserlet hook', priority: 10, timeoutMs: 5_000, retryOnFail: true },
  { event: 'db:lancedb:threshold:reached', category: 'infra', description: 'LanceDB meret kuszob hook', priority: 7, timeoutMs: 5_000, retryOnFail: true },
  { event: 'db:integrity:check', category: 'infra', description: 'Adatbazis integritasi ellenorzes hook', priority: 7, timeoutMs: 5_000, retryOnFail: true },
  { event: 'db:write:batch:completed', category: 'infra', description: 'Adatbazis batch write hook', priority: 6, timeoutMs: 5_000, retryOnFail: false },
  { event: 'property:analyzed', category: 'business', description: 'Ingatlan elemzesi hook', priority: 6, timeoutMs: 10_000, retryOnFail: true },
  { event: 'procurement:quote:received', category: 'business', description: 'Beszerzesi ajanlat erkezett hook', priority: 6, timeoutMs: 10_000, retryOnFail: true },
  { event: 'gmail:new:email', category: 'business', description: 'Uj Gmail level hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'calendar:deadline:approaching', category: 'business', description: 'Hatarido kozeledes hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'dashboard:deploy:completed', category: 'infra', description: 'Dashboard deploy befejezodott', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'build:failed', category: 'infra', description: 'Build failure hook', priority: 9, timeoutMs: 10_000, retryOnFail: true },
  { event: 'build:failed:retry', category: 'infra', description: 'Build retry hook', priority: 8, timeoutMs: 10_000, retryOnFail: true },
  { event: 'test:flaky:detected', category: 'infra', description: 'Flaky teszt hook', priority: 8, timeoutMs: 10_000, retryOnFail: true },
  { event: 'browser:selector:failed', category: 'infra', description: 'Browser selector failure hook', priority: 8, timeoutMs: 10_000, retryOnFail: true },
  { event: 'browser:session:created', category: 'infra', description: 'Browser session created hook', priority: 5, timeoutMs: 5_000, retryOnFail: false },
  { event: 'browser:session:restored', category: 'infra', description: 'Browser session restored hook', priority: 5, timeoutMs: 5_000, retryOnFail: false },
  { event: 'ollama:model:changed', category: 'infra', description: 'Ollama modell valtas hook', priority: 6, timeoutMs: 5_000, retryOnFail: false },
  { event: 'demand:forecast:completed', category: 'business', description: 'Demand forecast completed hook', priority: 6, timeoutMs: 10_000, retryOnFail: true },
  { event: 'federation:peer:connected', category: 'infra', description: 'Federation peer csatlakozas hook', priority: 6, timeoutMs: 5_000, retryOnFail: true },
  { event: 'federation:peer:disconnected', category: 'infra', description: 'Federation peer lecsatlakozas hook', priority: 7, timeoutMs: 5_000, retryOnFail: true },
  { event: 'federation:manifest:signed', category: 'infra', description: 'Federation manifest alairas hook', priority: 6, timeoutMs: 5_000, retryOnFail: true },
  { event: 'phoenix:agent:failed', category: 'security', description: 'Phoenix agent failure hook', priority: 9, timeoutMs: 5_000, retryOnFail: true },
  { event: 'paios:session:start', category: 'lifecycle', description: 'PAIOS session start hook', priority: 6, timeoutMs: 5_000, retryOnFail: false },
  { event: 'paios:session:end', category: 'lifecycle', description: 'PAIOS session end hook', priority: 6, timeoutMs: 5_000, retryOnFail: false },
  { event: 'nova:task:incoming', category: 'lifecycle', description: 'Nova task ingress hook', priority: 7, timeoutMs: 5_000, retryOnFail: false },
  { event: 'scheduler.task.started', category: 'cron', description: 'Scheduler task indult hook', priority: 7, timeoutMs: 5_000, retryOnFail: false },
  { event: 'scheduler.task.succeeded', category: 'cron', description: 'Scheduler task siker hook', priority: 7, timeoutMs: 5_000, retryOnFail: false },
  { event: 'scheduler.task.failed', category: 'cron', description: 'Scheduler task failure hook', priority: 8, timeoutMs: 5_000, retryOnFail: true },
  { event: 'cron:daily:morning', category: 'cron', description: 'Napi reggeli cron hook', priority: 6, timeoutMs: 10_000, retryOnFail: true },
  { event: 'cron:daily:briefing', category: 'cron', description: 'Napi briefing cron hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'cron:daily:financial:close', category: 'cron', description: 'Napi financial close hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'cron:weekly:monday', category: 'cron', description: 'Hetfoi cron hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'cron:weekly:friday:close', category: 'cron', description: 'Heti zaro cron hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'cron:quarterly', category: 'cron', description: 'Negyedeves cron hook', priority: 6, timeoutMs: 10_000, retryOnFail: true },
  { event: 'decision:triggered', category: 'learning', description: 'L5 decision analysis triggered hook', priority: 7, timeoutMs: 10_000, retryOnFail: false },
  { event: 'decision:scenarios_generated', category: 'learning', description: 'L5 decision scenarios generated hook', priority: 6, timeoutMs: 10_000, retryOnFail: false },
  { event: 'decision:action_selected', category: 'learning', description: 'L5 decision action selected hook', priority: 7, timeoutMs: 10_000, retryOnFail: true },
  { event: 'decision:action_executed', category: 'learning', description: 'L5 decision action executed hook', priority: 8, timeoutMs: 15_000, retryOnFail: true },
  { event: 'decision:rolled_back', category: 'learning', description: 'L5 decision action rolled back hook', priority: 8, timeoutMs: 15_000, retryOnFail: true },
  { event: 'decision:no_action', category: 'learning', description: 'L5 decision no action taken hook', priority: 6, timeoutMs: 10_000, retryOnFail: false },
];
