
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents",
  "version": "0.3.0",
  "versions": {
    "@openai/agents": "0.3.0",
    "@openai/agents-core": "workspace:*",
    "@openai/agents-openai": "workspace:*",
    "@openai/agents-realtime": "workspace:*",
    "openai": "^6"
  }
};

export default METADATA;
