import fs from "node:fs";
import path from "node:path";

import yaml from "js-yaml";

export type DocsConfigHealthStatus = "healthy" | "warning" | "critical";
export type DocsConfigSeverity = "low" | "medium" | "high" | "critical";

export interface MarkerDefinition {
  id: string;
  pattern: RegExp;
}

export interface SurfaceDefinition {
  name: string;
  path: string;
  kind: "doc" | "config" | "script";
  required: boolean;
  markers?: MarkerDefinition[];
}

export interface SurfaceSummary {
  name: string;
  path: string;
  kind: "doc" | "config" | "script";
  required: boolean;
  present: boolean;
  characters: number;
  lines: number;
  matchedMarkers: string[];
  expectedMarkers: string[];
}

export interface RuntimeKeySource {
  source: string;
  keys: string[];
}

export interface ConfigKeyCoverage {
  key: string;
  sources: string[];
  inDocs: string[];
  inExample: boolean;
  inYaml: boolean;
}

export interface DocsConfigSotSnapshot {
  checkedAt: string;
  rootDir: string;
  documents: {
    surfaces: SurfaceSummary[];
    requiredCount: number;
    presentRequiredCount: number;
    managedCount: number;
    managedHealthyCount: number;
    coveragePercent: number;
    managedCoveragePercent: number;
    missingRequired: string[];
    missingManagedMarkers: string[];
  };
  config: {
    surfaces: SurfaceSummary[];
    runtimeKeySources: RuntimeKeySource[];
    runtimeKeys: string[];
    exampleKeys: string[];
    yamlBindings: string[];
    keyCoverage: ConfigKeyCoverage[];
    docsKeyCoveragePercent: number;
    exampleKeyCoveragePercent: number;
    missingFromDocs: ConfigKeyCoverage[];
    missingFromExample: ConfigKeyCoverage[];
    yamlBindingsMissingFromRuntime: string[];
  };
  summary: {
    score: number;
    status: DocsConfigHealthStatus;
    docsStatus: DocsConfigHealthStatus;
    configStatus: DocsConfigHealthStatus;
  };
  warnings: string[];
}

const DOC_STATS_MARKER: MarkerDefinition = {
  id: "doc-stats-block",
  pattern: /<!-- DOC_STATS_START -->[\s\S]*?<!-- DOC_STATS_END -->/u,
};

const GENERATED_MASTER_CONTEXT_MARKER: MarkerDefinition = {
  id: "master-context-footer",
  pattern: /\*\*Ez a dokumentum automatikusan generált\. Ne szerkeszd kézzel!\*\*/u,
};

const TRACKS_GENERATED_MARKER: MarkerDefinition = {
  id: "tracks-generated-header",
  pattern: /\*Auto-generated by Track State Manager v2\.0\*/u,
};

const PAIOS_YAML_MARKER: MarkerDefinition = {
  id: "paios-yaml-header",
  pattern: /PAIOS 1\.0 Unified Configuration/u,
};

const CONFIG_SCHEMA_MARKER: MarkerDefinition = {
  id: "config-schema-header",
  pattern: /Config Validation with Zod/u,
};

const BIFROST_MARKER: MarkerDefinition = {
  id: "bifrost-header",
  pattern: /Bifrost Gateway - Multi-Provider LLM Routing/u,
};

const CLI_CONFIG_MARKER: MarkerDefinition = {
  id: "cli-config-schema",
  pattern: /BrunellaSettingsSchema/u,
};

const DOCUMENT_SURFACES: SurfaceDefinition[] = [
  {
    name: "README.md",
    path: "README.md",
    kind: "doc",
    required: true,
    markers: [DOC_STATS_MARKER],
  },
  {
    name: "BRUNELLA_MASTER_CONTEXT.md",
    path: "BRUNELLA_MASTER_CONTEXT.md",
    kind: "doc",
    required: true,
    markers: [GENERATED_MASTER_CONTEXT_MARKER],
  },
  {
    name: "RENDSZER.md",
    path: "RENDSZER.md",
    kind: "doc",
    required: true,
  },
  {
    name: "conductor/tracks.md",
    path: "conductor/tracks.md",
    kind: "doc",
    required: true,
    markers: [TRACKS_GENERATED_MARKER],
  },
  {
    name: "BOOTSTRAP.md",
    path: "BOOTSTRAP.md",
    kind: "doc",
    required: false,
    markers: [DOC_STATS_MARKER],
  },
  {
    name: "PROJEKT_DIAGRAM.md",
    path: "PROJEKT_DIAGRAM.md",
    kind: "doc",
    required: false,
    markers: [DOC_STATS_MARKER],
  },
  {
    name: ".ai/BOOTSTRAP.md",
    path: ".ai/BOOTSTRAP.md",
    kind: "doc",
    required: false,
    markers: [DOC_STATS_MARKER],
  },
  {
    name: ".vscode/BOOTSTRAP.md",
    path: ".vscode/BOOTSTRAP.md",
    kind: "doc",
    required: false,
    markers: [DOC_STATS_MARKER],
  },
  {
    name: "scripts/update_master_context.ts",
    path: "scripts/update_master_context.ts",
    kind: "script",
    required: false,
  },
  {
    name: "scripts/sync_doc_stats.ts",
    path: "scripts/sync_doc_stats.ts",
    kind: "script",
    required: false,
  },
  {
    name: "scripts/sync_docs.ts",
    path: "scripts/sync_docs.ts",
    kind: "script",
    required: false,
  },
];

const CONFIG_SURFACES: SurfaceDefinition[] = [
  {
    name: ".env.example",
    path: ".env.example",
    kind: "config",
    required: true,
  },
  {
    name: "paios.config.yaml",
    path: "paios.config.yaml",
    kind: "config",
    required: true,
    markers: [PAIOS_YAML_MARKER],
  },
  {
    name: "src/config/schema.ts",
    path: "src/config/schema.ts",
    kind: "config",
    required: true,
    markers: [CONFIG_SCHEMA_MARKER],
  },
  {
    name: "src/config/index.ts",
    path: "src/config/index.ts",
    kind: "config",
    required: true,
  },
  {
    name: "src/config/paiosConfig.ts",
    path: "src/config/paiosConfig.ts",
    kind: "config",
    required: true,
    markers: [CONFIG_SCHEMA_MARKER],
  },
  {
    name: "src/core/bifrost_gateway.ts",
    path: "src/core/bifrost_gateway.ts",
    kind: "config",
    required: true,
    markers: [BIFROST_MARKER],
  },
  {
    name: "src/utils/cliConfig.ts",
    path: "src/utils/cliConfig.ts",
    kind: "config",
    required: true,
    markers: [CLI_CONFIG_MARKER],
  },
];

const CORE_DOC_FILES = [
  "README.md",
  "BRUNELLA_MASTER_CONTEXT.md",
  "RENDSZER.md",
  "BOOTSTRAP.md",
  "PROJEKT_DIAGRAM.md",
  ".ai/BOOTSTRAP.md",
  ".vscode/BOOTSTRAP.md",
  "conductor/tracks.md",
];

const CONFIG_KEY_SOURCE_FILES = [
  "src/config/schema.ts",
  "src/config/index.ts",
  "src/config/paiosConfig.ts",
  "src/core/bifrost_gateway.ts",
  "src/utils/cliConfig.ts",
];

const DOC_KEY_SOURCE_FILES = [
  ...CORE_DOC_FILES,
  ".env.example",
  "paios.config.yaml",
];

function uniqueSorted(values: string[]): string[] {
  return Array.from(new Set(values.map((value) => value.trim()).filter(Boolean))).sort((left, right) =>
    left.localeCompare(right, undefined, { sensitivity: "base" }),
  );
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readTextFileOrThrow(absolutePath: string): string | null {
  if (!fs.existsSync(absolutePath)) {
    return null;
  }

  return fs.readFileSync(absolutePath, "utf8").replace(/^\uFEFF/, "");
}

function countLines(content: string): number {
  if (content.length === 0) {
    return 0;
  }

  return content.split(/\r?\n/u).length;
}

function loadSurface(rootDir: string, definition: SurfaceDefinition): { summary: SurfaceSummary; content: string | null } {
  const absolutePath = path.resolve(rootDir, definition.path);
  const content = readTextFileOrThrow(absolutePath);
  const markers = definition.markers ?? [];
  const matchedMarkers = content === null
    ? []
    : markers.filter((marker) => marker.pattern.test(content)).map((marker) => marker.id);

  return {
    summary: {
      name: definition.name,
      path: absolutePath,
      kind: definition.kind,
      required: definition.required,
      present: content !== null,
      characters: content?.length ?? 0,
      lines: content === null ? 0 : countLines(content),
      matchedMarkers,
      expectedMarkers: markers.map((marker) => marker.id),
    },
    content,
  };
}

function scanEnvAssignments(content: string): string[] {
  const keys: string[] = [];
  for (const rawLine of content.split(/\r?\n/u)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }

    const match = line.match(/^([A-Z0-9_]+)\s*=/u);
    if (match) {
      keys.push(match[1]);
    }
  }

  return uniqueSorted(keys);
}

function scanProcessEnvReferences(content: string): string[] {
  const matches = content.matchAll(/process\.env\.([A-Z0-9_]+)/gu);
  return uniqueSorted(Array.from(matches, (match) => match[1]));
}

function collectYamlBindings(value: unknown, bindings: Set<string>): void {
  if (Array.isArray(value)) {
    for (const entry of value) {
      collectYamlBindings(entry, bindings);
    }
    return;
  }

  if (!isRecord(value)) {
    return;
  }

  for (const [key, child] of Object.entries(value)) {
    if (key.endsWith("_env") && typeof child === "string" && child.trim().length > 0) {
      bindings.add(child.trim());
    }

    collectYamlBindings(child, bindings);
  }
}

function parseYamlBindings(content: string, absolutePath: string): string[] {
  let parsed: unknown;

  try {
    parsed = yaml.load(content);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to parse YAML config at ${absolutePath}: ${message}`);
  }

  const bindings = new Set<string>();
  collectYamlBindings(parsed, bindings);
  return uniqueSorted(Array.from(bindings));
}

function buildRuntimeKeySources(rootDir: string): Array<{ source: string; keys: string[]; content?: string }> {
  const sources: Array<{ source: string; keys: string[]; content?: string }> = [];

  for (const definition of CONFIG_SURFACES) {
    if (definition.name === ".env.example") {
      continue;
    }

    const absolutePath = path.resolve(rootDir, definition.path);
    const content = readTextFileOrThrow(absolutePath);
    if (content === null) {
      sources.push({ source: definition.name, keys: [] });
      continue;
    }

    if (definition.path === "paios.config.yaml") {
      sources.push({ source: definition.name, keys: parseYamlBindings(content, absolutePath), content });
      continue;
    }

    sources.push({ source: definition.name, keys: scanProcessEnvReferences(content), content });
  }

  return sources;
}

function buildDocsKeyIndex(rootDir: string, runtimeKeys: string[]): Map<string, string[]> {
  const index = new Map<string, string[]>();

  for (const docPath of DOC_KEY_SOURCE_FILES) {
    const absolutePath = path.resolve(rootDir, docPath);
    const content = readTextFileOrThrow(absolutePath);
    if (content === null) {
      continue;
    }

    for (const key of runtimeKeys) {
      const pattern = new RegExp(`\\b${escapeRegExp(key)}\\b`, "u");
      if (!pattern.test(content)) {
        continue;
      }

      const current = index.get(key) ?? [];
      current.push(docPath);
      index.set(key, uniqueSorted(current));
    }
  }

  return index;
}

function buildExampleKeys(rootDir: string): string[] {
  const absolutePath = path.resolve(rootDir, ".env.example");
  const content = readTextFileOrThrow(absolutePath);
  if (content === null) {
    return [];
  }

  return scanEnvAssignments(content);
}

function buildKeyCoverage(
  runtimeKeySources: Array<{ source: string; keys: string[] }>,
  docsKeyIndex: Map<string, string[]>,
  exampleKeys: string[],
  yamlBindings: string[],
): ConfigKeyCoverage[] {
  const runtimeKeys = uniqueSorted(runtimeKeySources.flatMap((source) => source.keys));
  const exampleSet = new Set(exampleKeys);
  const yamlSet = new Set(yamlBindings);

  return runtimeKeys.map((key) => ({
    key,
    sources: uniqueSorted(
      runtimeKeySources
        .filter((source) => source.keys.includes(key))
        .map((source) => source.source),
    ),
    inDocs: docsKeyIndex.get(key) ?? [],
    inExample: exampleSet.has(key),
    inYaml: yamlSet.has(key),
  }));
}

function calculateHealthScore(
  documentCoveragePercent: number,
  generatedCoveragePercent: number,
  docsKeyCoveragePercent: number,
  exampleKeyCoveragePercent: number,
  yamlBindingsMissingFromRuntimeCount: number,
): number {
  const base =
    documentCoveragePercent * 0.4 +
    generatedCoveragePercent * 0.2 +
    docsKeyCoveragePercent * 0.25 +
    exampleKeyCoveragePercent * 0.15;

  const penalty = Math.min(20, yamlBindingsMissingFromRuntimeCount * 5);
  return Math.max(0, Math.round(base - penalty));
}

function classifyHealth(score: number, hardFailure: boolean): DocsConfigHealthStatus {
  if (hardFailure) {
    return "critical";
  }
  if (score >= 85) {
    return "healthy";
  }
  if (score >= 65) {
    return "warning";
  }
  return "critical";
}

export function buildDocsConfigSotSnapshot(rootDir = process.cwd()): DocsConfigSotSnapshot {
  const checkedAt = new Date().toISOString();
  const resolvedRoot = path.resolve(rootDir);

  const documentLoads = DOCUMENT_SURFACES.map((definition) => loadSurface(resolvedRoot, definition));
  const configLoads = CONFIG_SURFACES.map((definition) => loadSurface(resolvedRoot, definition));

  const documentSurfaces = documentLoads.map((entry) => entry.summary);
  const configSurfaces = configLoads.map((entry) => entry.summary);

  const requiredDocumentSurfaces = documentSurfaces.filter((surface) => surface.required);
  const managedDocumentSurfaces = documentSurfaces.filter((surface) => surface.expectedMarkers.length > 0);

  const missingRequired = requiredDocumentSurfaces.filter((surface) => !surface.present).map((surface) => surface.name);
  const missingManagedMarkers = managedDocumentSurfaces
    .filter((surface) => surface.present && surface.matchedMarkers.length === 0)
    .map((surface) => surface.name);

  const requiredCount = requiredDocumentSurfaces.length;
  const presentRequiredCount = requiredDocumentSurfaces.filter((surface) => surface.present).length;
  const managedCount = managedDocumentSurfaces.length;
  const managedHealthyCount = managedDocumentSurfaces.filter((surface) => surface.present && surface.matchedMarkers.length > 0).length;

  const runtimeKeySources = buildRuntimeKeySources(resolvedRoot);
  const runtimeKeys = uniqueSorted(runtimeKeySources.flatMap((source) => source.keys));
  const codeRuntimeKeys = uniqueSorted(
    runtimeKeySources
      .filter((source) => source.source !== "paios.config.yaml")
      .flatMap((source) => source.keys),
  );
  const exampleKeys = buildExampleKeys(resolvedRoot);
  const yamlBindings = runtimeKeySources
    .find((source) => source.source === "paios.config.yaml")
    ?.keys ?? [];
  const docsKeyIndex = buildDocsKeyIndex(resolvedRoot, runtimeKeys);
  const keyCoverage = buildKeyCoverage(runtimeKeySources, docsKeyIndex, exampleKeys, yamlBindings);

  const missingFromDocs = keyCoverage.filter((entry) => entry.inDocs.length === 0);
  const missingFromExample = keyCoverage.filter((entry) => !entry.inExample);
  const yamlBindingsMissingFromRuntime = yamlBindings.filter((binding) => !codeRuntimeKeys.includes(binding));

  const docsKeyCoveragePercent = runtimeKeys.length === 0
    ? 100
    : Math.round((runtimeKeys.length - missingFromDocs.length) / runtimeKeys.length * 100);
  const exampleKeyCoveragePercent = runtimeKeys.length === 0
    ? 100
    : Math.round((runtimeKeys.length - missingFromExample.length) / runtimeKeys.length * 100);
  const documentCoveragePercent = requiredCount === 0
    ? 100
    : Math.round(presentRequiredCount / requiredCount * 100);
  const generatedCoveragePercent = managedCount === 0
    ? 100
    : Math.round(managedHealthyCount / managedCount * 100);

  const score = calculateHealthScore(
    documentCoveragePercent,
    generatedCoveragePercent,
    docsKeyCoveragePercent,
    exampleKeyCoveragePercent,
    yamlBindingsMissingFromRuntime.length,
  );

  const hardFailure = missingRequired.length > 0;
  const docsStatus = classifyHealth(
    Math.round((documentCoveragePercent + generatedCoveragePercent) / 2),
    missingRequired.length > 0,
  );
  const configStatus = classifyHealth(
    Math.round((docsKeyCoveragePercent + exampleKeyCoveragePercent) / 2),
    yamlBindingsMissingFromRuntime.length > 0 && runtimeKeys.length > 0,
  );

  const status = classifyHealth(score, hardFailure);

  return {
    checkedAt,
    rootDir: resolvedRoot,
    documents: {
      surfaces: documentSurfaces,
      requiredCount,
      presentRequiredCount,
      managedCount,
      managedHealthyCount,
      coveragePercent: documentCoveragePercent,
      managedCoveragePercent: generatedCoveragePercent,
      missingRequired,
      missingManagedMarkers,
    },
    config: {
      surfaces: configSurfaces,
      runtimeKeySources: runtimeKeySources.map((source) => ({
        source: source.source,
        keys: source.keys,
      })),
      runtimeKeys,
      exampleKeys,
      yamlBindings,
      keyCoverage,
      docsKeyCoveragePercent,
      exampleKeyCoveragePercent,
      missingFromDocs,
      missingFromExample,
      yamlBindingsMissingFromRuntime,
    },
    summary: {
      score,
      status,
      docsStatus,
      configStatus,
    },
    warnings: [
      ...missingRequired.map((name) => `Missing required documentation surface: ${name}`),
      ...missingManagedMarkers.map((name) => `Managed marker missing from: ${name}`),
      ...yamlBindingsMissingFromRuntime.map((binding) => `PAIOS YAML binding has no runtime consumer: ${binding}`),
    ],
  };
}

export function renderDocsConfigSotMarkdown(snapshot: DocsConfigSotSnapshot): string {
  const docsLines = snapshot.documents.surfaces
    .filter((surface) => surface.kind === "doc")
    .map((surface) => `| ${surface.name} | ${surface.present ? "present" : "missing"} | ${surface.matchedMarkers.join(", ") || "-"} |`);

  const configLines = snapshot.config.surfaces
    .filter((surface) => surface.kind === "config")
    .map((surface) => `| ${surface.name} | ${surface.present ? "present" : "missing"} | ${surface.lines} |`);

  return [
    "# Documentation / Config SOT Snapshot",
    "",
    `- Checked at: **${snapshot.checkedAt}**`,
    `- Health: **${snapshot.summary.status}** (${snapshot.summary.score}/100)`,
    `- Docs coverage: **${snapshot.documents.coveragePercent}%**`,
    `- Config coverage: **${snapshot.config.docsKeyCoveragePercent}% / ${snapshot.config.exampleKeyCoveragePercent}%**`,
    "",
    "## Documents",
    "",
    "| Surface | State | Markers |",
    "| --- | --- | --- |",
    ...docsLines,
    "",
    "## Config surfaces",
    "",
    "| Surface | State | Lines |",
    "| --- | --- | --- |",
    ...configLines,
    "",
    "## Drift",
    "",
    snapshot.warnings.length === 0 ? "- None" : snapshot.warnings.map((warning) => `- ${warning}`).join("\n"),
  ].join("\n");
}

